### ISSUE TITLE
Search limitation:  If I add a ISWC code, and then search for it, no results show

### ISSUE THREAD

**Issue by kenumezaki** [cardstack/dotbc-bugs#19]

**Comment by kenumezaki** [comment]
I added an ISWC code to Jive At Five on the Works side.  T0700884521.  I then search by that identifier but nothing shows up.  Search should be dynamic to any added information.  Would like to understand the limitation if there is any.

**Comment by chloedotbc** [comment]
I think this is actually because the ISWC codes aren't saving - rather than going from an "edited" to a "published" state - the ISWC changes I've made aren't saving either. If I refresh the window, the ISWC I just added disappears.

Then, if I go in to try to add it again - the fields appear to be locked even when in "edit" mode.

<img width="1371" alt="screen shot 2019-01-26 at 15 47 40" src="https://user-images.githubusercontent.com/46965257/51789589-113a2880-2182-11e9-9a08-05a5a5ea84a3.png">

**Comment by dnaidionov** [comment]
This is related to #23. Should be fixed now

**Comment by dnaidionov** [comment]
we currently don't search by ISWC, but will expand search to all fields soon

**Comment by chloedotbc** [comment]
It's a problem if we can't search by ISWC.

**Comment by dnaidionov** [comment]
fixed by cardstack/dotbc#303
