### ISSUE TITLE
Release Card changes - information needs to be moved and/or exposed

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#25]
See screenshot below for changes:
<img width="1362" alt="screen shot 2019-01-26 at 19 18 57" src="https://user-images.githubusercontent.com/46965257/51791778-638a4200-21a0-11e9-9c66-d32bd10a8a18.png">

**Comment by dnaidionov** [comment]
- Album data will be shown (tracked in cardstack/dotbc#253, cardstack/dotbc#276
- What you refer as dummy data is actually a bug, tracked in cardstack/dotbc#284
- Titles on the release details are coming from the release section of the import file. Master section also has title fields, and they are used on master recording card. Data in them happen to be the same, but it doesn't have to, they are independent fields. 
- ISRC is displayed in release because it was in the release section of the import file. We just uploaded all the codes from release section to release and codes from master section to master. Master section also has isrc. 
- Release format is not present in import file that's why it's empty, but the idea is like you specified
- Release Type is coming from import file. According to DDEX it can be `TrackRelease` or `VideoTrackRelease` for tracks, and the values you specified for albums. Album information (see above) will also include release type
