### ISSUE TITLE
When you scroll down the page of a matched master/work - the "request access button" disappears at the top.

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#32]
# Summary
Not sure if it's a bug or just because the environment is being worked on "live" -  but  in case it's a bug I thought I'd log it.

I was on this track: https://pouty.pizza/songs/603497138562-R9 - and saw the "request access" button at the top right, but when I had scrolled down to look at the work cards for a few seconds and then scrolled back up, the button was gone.

# Steps to reproduce
1. Search song that's matched
2. Scroll down to the bottom of the page
3. Wait a few seconds 
4. Scroll up.

# Expected result
Button is still there

# Actual result
Button is gone

# Environment
* Operating system:  OS 10.12.6
* Browser: Chrome

**Comment by dnaidionov** [comment]
That's because you have already submitted request to get access. It took a bit to figure the status and adjust the display of the button. To avoid confusion we will change the UI start with hidden and to show it only if there's no pending or approved status, and display the pending status if request has already been submitted. 
tracked in cardstack/dotbc#315 and cardstack/dotbc#336
